### ISSUE TITLE
Seg Fault after upgrading to 1.0.3

### ISSUE THREAD

**Issue by robolson** [lsegal/ripper18#5]
I am using ripper via the [rails_best_practices gem](https://github.com/flyerhzm/rails_best_practices). After jumping to 1.0.3 I suddenly get this error. Works fine with 1.0.2. Sorry I don't have more information.

```
/Users/rob/.rvm/gems/ree-1.8.7-2011.03/gems/ripper-1.0.3/lib/ripper/../../ext/ripper.bundle: [BUG] Segmentation fault
ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-darwin10.6.0], MBARI 0x6770, Ruby Enterprise Edition 2011.03

Abort trap: 6
```

**Comment by lsegal** [comment]
Reproduction steps would be helpful, can you list exactly what you're doing with the rails_best_practices gem to make ripper segfault? If I can reproduce I can narrow down.

**Comment by lsegal** [comment]
FWIW I just tried out the gem on 1.8.7p249 (shipped with Lion) and no segfaults when running on a small test app. I couldn't install REE, I was running into compile issues (segfaults, coincidentally!), so I can't test there.

**Comment by robolson** [comment]
I will work towards some steps to reproduce and respond back.

**Comment by robolson** [comment]
I do not know what changed but this no longer happens with 1.0.5.
