### ISSUE TITLE
1.0.3 - ripper.o: File format not recognized

### ISSUE THREAD

**Issue by peternash** [lsegal/ripper18#6]
Error trying to install ripper 1.0.3 on RHEL 5 with REE 1.8.7-2011.03 (see below)   Version 1.0.2.1 installed ok.

Fetching: ripper-1.0.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing ripper:
        ERROR: Failed to build gem native extension.

```
    /opt/ruby-enterprise-1.8.7-2011.03/bin/ruby extconf.rb
```

checking for bison... yes
creating Makefile

make
gcc -shared -o ripper.so ripper.o -L. -L/opt/ruby-enterprise-1.8.7-2011.03/lib -Wl,-R/opt/ruby-enterprise-1.8.                     7-2011.03/lib -L.  -rdynamic -Wl,-export-dynamic    -L/opt/local/lib -lrt -ldl -lcrypt -lm   -lc
ripper.o: file not recognized: File format not recognized
collect2: ld returned 1 exit status
make: **\* [ripper.so] Error 1

**Comment by lsegal** [comment]
Are you sure this is not an environment issue? can you try Ruby 1.8.7, not REE? "file format not recognized" on a file that was created locally on your machine seems like something with your setup.

**Comment by peternash** [comment]
Hi - we've been using REE for quite a while on a number of servers so fairly sure it's not environment.  However, just confirmed exactly the same error on:

REE 1.8.7-2011.03 on 64 bit RHEL 5
REE 1.8.7-2010.02 on 32 bit RHEL 5
Ruby 1.8.7 (2011-06-30 patchlevel 352) on 32 bit Fedora 14

**Comment by lsegal** [comment]
Thanks, I've identified the issue. Fix coming your way in a few.

**Comment by lsegal** [comment]
Hmm, didn't seem to have worked. It works fine when installing locally, but a remote gem install fails. Some weird rubygems issue, perhaps?

Try the following:

```
$ git clone git://github.com/lsegal/ripper18
$ cd ripper18
$ rake install
```

**Comment by lsegal** [comment]
Oh duh, the ripper.o leaked into the gem. I'm about to release an update.

**Comment by lsegal** [comment]
gem install should work now. Thanks for reporting!

**Comment by peternash** [comment]
That's great - 1.0.5 installing fine - thanks for your quick response.
