### ISSUE TITLE
Error Installing ripper

### ISSUE THREAD

**Issue by Ramesh7** [lsegal/ripper18#8]
Hi All,
when i run command "rails server" that time it showing me following error. I am using jruby(1.6.7.2) in that ruby version is 1.8.7 

Building native extensions.  This could take a while...
ERROR:  Error installing ripper:
    ERROR: Failed to build gem native extension.

```
    /home/dev/.rvm/rubies/jruby-1.6.7.2/bin/jruby extconf.rb
```

WARNING: JRuby does not support native extensions or the `mkmf' library very well.
Check http://kenai.com/projects/jruby/pages/Home for alternatives.
checking for bison... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/home/dev/.rvm/rubies/jruby-1.6.7.2/bin/jruby

Gem files will remain installed in /home/dev/.rvm/gems/jruby-1.6.7.2/gems/ripper-1.0.5 for inspection.
Results logged to /home/dev/.rvm/gems/jruby-1.6.7.2/gems/ripper-1.0.5/ext/gem_make.out

And i also try with jruby 1.6.7.2 in that ruby 1.9.2 that time it showing me following error is :

LoadError: no such file to load -- ripper
          require at org/jruby/RubyKernel.java:1042
          require at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251
  load_dependency at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236
          require at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251
           (root) at /home/dev/.rvm/rubies/jruby-1.6.7.2/lib/ruby/1.9/ripper/core.rb:11
          require at org/jruby/RubyKernel.java:1042
          require at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251
  load_dependency at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236
          require at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251
           (root) at /home/dev/.rvm/rubies/jruby-1.6.7.2/lib/ruby/1.9/ripper/core.rb:1
          require at org/jruby/RubyKernel.java:1042
          require at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251
  load_dependency at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236
          require at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251
           (root) at /home/dev/.rvm/rubies/jruby-1.6.7.2/lib/ruby/1.9/ripper.rb:2
          require at org/jruby/RubyKernel.java:1042
          require at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251
  load_dependency at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236
          require at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251
           (root) at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/code_analyzer-0.2.0/lib/code_analyzer.rb:25
          require at org/jruby/RubyKernel.java:1042
          require at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/rails_best_practices-1.11.1/lib/rails_best_practices.rb:68
             each at org/jruby/RubyArray.java:1615
          require at /home/dev/.rvm/gems/jruby-1.6.7.2@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:66
             each at org/jruby/RubyArray.java:1615
          require at /home/dev/.rvm/gems/jruby-1.6.7.2@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:55
          require at /home/dev/.rvm/gems/jruby-1.6.7.2@global/gems/bundler-1.2.1/lib/bundler.rb:128
           (root) at /home/dev/Desktop/Ramesh/MAP_Docs/CurrentMAP/trunk/config/application.rb:7
          require at org/jruby/RubyKernel.java:1042
           (root) at /home/dev/Desktop/Ramesh/MAP_Docs/CurrentMAP/trunk/config/application.rb:53
              tap at org/jruby/RubyKernel.java:1787
           (root) at /home/dev/.rvm/gems/jruby-1.6.7.2/gems/railties-3.2.8/lib/rails/commands.rb:50
          require at org/jruby/RubyKernel.java:1042
           (root) at script/rails:6
Please help me out.

**Comment by lsegal** [comment]
Ripper does not support JRuby. Ideally we should be building platform specific gems, but this is currently not being done.

**Comment by Ramesh7** [comment]
Is there any way that I can make ripper work? 'Coz according to the project requirement, both the JRuby and Ruby has to run side by side.

**Comment by lsegal** [comment]
Which project is this for? JRuby has its own AST parser library, and no, Ripper cannot work in JRuby. Ripper is very specific to the MRI implementation.

**Comment by Ramesh7** [comment]
I was using "rails_best_practices" gem that's why it giving me above error. I removed it from gemfile and now it working fine.

**Comment by lsegal** [comment]
You might want to specify that gem under `:platforms => :mri` so that it's only used inside of non-JRuby installs. I don't see any reason why you need to run the gem in JRuby though-- it is probably your app that requires JRuby, not the gem.

I am closing this issue. Please feel free to open a new issue if you find a bug in this library!

**Comment by Ramesh7** [comment]
ya sure thanx a lot
